import type { DemoWords } from "./words";

/** The demo in English, the same boards word for word. */
export const DEMO_EN: DemoWords = {
  kanban: {
    name: "Webshop",
    key: "WEB",
    description:
      "Running and improving the webshop. Continuous flow, at most three things in progress.",
    structure: {
      areas: ["Payments", "Catalogue", "Delivery", "Front page", "Platform"],
      themes: [
        { name: "Self-service", color: "moss" },
        { name: "Conversion", color: "clay" },
        { name: "Stable operations", color: "sage" },
      ],
      epics: [
        {
          title: "Customers can pay the way they want",
          doneWhen: "MobilePay, cards and gift cards work in checkout on every device",
          area: "Payments",
          themes: ["Conversion", "Self-service"],
          quarterOffset: 1,
          features: [
            {
              title: "Customers can pay with MobilePay on every device",
              doneWhen: "The payment completes on iPhone and Android without emptying the basket",
            },
            {
              title: "Customers can pay with gift cards",
              doneWhen: "A gift card can be redeemed in full or in part in checkout",
            },
          ],
        },
        {
          title: "Customers find the product without searching",
          doneWhen: "Search and sorting are used in 40 % of sessions and the return rate drops",
          area: "Catalogue",
          themes: ["Conversion"],
          quarterOffset: 2,
          agedDays: 200,
          features: [
            {
              title: "Customers can sort and filter the categories",
              doneWhen: "Price, popularity and newness can be chosen on every category page",
            },
            {
              title: "Customers can read and write reviews",
              doneWhen: "Reviews show on the product page and can be written after a purchase",
            },
          ],
        },
        {
          title: "We can deploy without downtime",
          doneWhen: "Three deployments in a row with no downtime and no manual steps",
          area: "Platform",
          themes: ["Stable operations"],
          enabler: "infrastructure",
          features: [
            {
              title: "Deployment happens automatically from main",
              doneWhen: "A green pipeline deploys without anybody pressing anything",
            },
          ],
        },
      ],
    },
    cards: [
      {
        title: "Customers cannot pay with MobilePay on iPhone",
        column: "doing",
        priority: "urgent",
        estimate: 3,
        description: "Happens after returning from the MobilePay app. The basket is empty.",
        checklist: ["Reproduce it", "Find the cause", "Fix and test on a real phone"],
        dueOffset: 1,
        feature: "Customers can pay with MobilePay on every device",
        bug: true,
      },
      {
        title: "Newsletter sign-up in the footer",
        column: "doing",
        estimate: 2,
        dueOffset: 4,
        area: "Front page",
      },
      {
        title: "Faster images on product pages",
        column: "doing",
        estimate: 5,
        blocked: "Waiting for new photos from the photographer",
        area: "Catalogue",
      },
      {
        title: "Sort by price in categories",
        column: "doing",
        estimate: 3,
        feature: "Customers can sort and filter the categories",
      },
      {
        title: "Gift cards can be redeemed in checkout",
        column: "todo",
        estimate: 8,
        priority: "high",
        feature: "Customers can pay with gift cards",
      },
      {
        title: "Update the terms of sale",
        column: "todo",
        estimate: 1,
        dueOffset: -2,
        area: "Front page",
      },
      {
        title: "Blue/green setup of the web servers",
        column: "todo",
        estimate: 5,
        feature: "Deployment happens automatically from main",
        enabler: "infrastructure",
      },
      {
        title: "Seasonal banner on the front page",
        column: "todo",
        estimate: 2,
        area: "Front page",
      },
      {
        title: "Return form customers fill in themselves",
        column: "backlog",
        estimate: 5,
        area: "Delivery",
      },
      {
        title: "Filter by size and colour",
        column: "backlog",
        estimate: 5,
        feature: "Customers can sort and filter the categories",
      },
      {
        title: "Write a review after a purchase",
        column: "backlog",
        estimate: 8,
        feature: "Customers can read and write reviews",
      },
      { title: "Wish list", column: "backlog", area: "Catalogue" },
      {
        title: "Gift cards can be bought as a gift",
        column: "backlog",
        estimate: 5,
        feature: "Customers can pay with gift cards",
      },
      { title: "Delivery to parcel shops", column: "done", estimate: 5, area: "Delivery" },
      { title: "Discount codes", column: "done", estimate: 3, area: "Payments" },
      { title: "Search that tolerates typos", column: "done", estimate: 5, area: "Catalogue" },
      {
        title: "A cookie banner that is not annoying",
        column: "done",
        estimate: 2,
        area: "Front page",
      },
      { title: "Order confirmation by mail", column: "done", estimate: 3, area: "Payments" },
      {
        title: "Build pipeline on every commit",
        column: "done",
        estimate: 5,
        feature: "Deployment happens automatically from main",
      },
      {
        title: "Upgrade the Node version",
        column: "done",
        estimate: 3,
        area: "Platform",
        enabler: "infrastructure",
      },
      {
        title: "MobilePay as a payment method",
        column: "done",
        estimate: 8,
        description: "First version in checkout, desktop only.",
        feature: "Customers can pay with MobilePay on every device",
      },
      {
        title: "MobilePay logo in checkout",
        column: "done",
        estimate: 1,
        feature: "Customers can pay with MobilePay on every device",
      },
      {
        title: "Receipt after a MobilePay payment",
        column: "done",
        estimate: 2,
        feature: "Customers can pay with MobilePay on every device",
      },
      {
        title: "Timeout when MobilePay does not respond",
        column: "done",
        estimate: 3,
        description: "Checkout hung for two minutes when the app did not respond.",
        feature: "Customers can pay with MobilePay on every device",
        bug: true,
      },
      {
        title: "Migrations run automatically",
        column: "done",
        estimate: 3,
        feature: "Deployment happens automatically from main",
      },
      {
        title: "Logging gathered in one place",
        column: "done",
        estimate: 5,
        description: "We searched three systems every time something went wrong.",
        area: "Platform",
        enabler: "infrastructure",
      },
      { title: "Shipping prices by weight", column: "done", estimate: 5, area: "Delivery" },
      {
        title: "Tracking link in the order confirmation",
        column: "done",
        estimate: 2,
        area: "Delivery",
      },
      {
        title: "Sort by popularity",
        column: "done",
        estimate: 3,
        feature: "Customers can sort and filter the categories",
      },
      {
        title: "Number of items next to each filter",
        column: "done",
        estimate: 2,
        feature: "Customers can sort and filter the categories",
      },
      {
        title: "Filter by brand",
        column: "done",
        estimate: 5,
        feature: "Customers can sort and filter the categories",
      },
      {
        title: "Filters are remembered when going back",
        column: "done",
        estimate: 3,
        description:
          "The chosen filters disappeared when the customer went back from a product page.",
        feature: "Customers can sort and filter the categories",
        bug: true,
      },
      {
        title: "Orders were charged twice",
        column: "done",
        estimate: 3,
        description: "A double click on the pay button created two orders.",
        area: "Payments",
        bug: true,
      },
      { title: "Invoice as a payment method", column: "done", estimate: 5, area: "Payments" },
      {
        title: "Reviews show on the product page",
        column: "done",
        estimate: 5,
        description: "Display only; reviews are still written in the old system.",
        feature: "Customers can read and write reviews",
      },
      {
        title: "Average rating in the category",
        column: "done",
        estimate: 3,
        feature: "Customers can read and write reviews",
      },
      {
        title: "Report a review",
        column: "done",
        estimate: 2,
        feature: "Customers can read and write reviews",
      },
      {
        title: "Data model for gift cards",
        column: "done",
        estimate: 5,
        feature: "Customers can pay with gift cards",
      },
      {
        title: "Gift card balance can be looked up",
        column: "done",
        estimate: 3,
        description: "Customer service needs to see what is left on a card.",
        feature: "Customers can pay with gift cards",
      },
      {
        title: "Expiry date on gift cards",
        column: "done",
        estimate: 2,
        feature: "Customers can pay with gift cards",
      },
      {
        title: "Roll back with one click",
        column: "done",
        estimate: 5,
        description: "The previous version can be put back into service without manual steps.",
        feature: "Deployment happens automatically from main",
      },
      {
        title: "Image handling out of the monolith",
        column: "done",
        estimate: 8,
        area: "Platform",
        enabler: "architecture",
      },
      {
        title: "Sold-out items at the bottom of the list",
        column: "done",
        estimate: 2,
        area: "Catalogue",
      },
      {
        title: "New front page for the autumn campaign",
        column: "done",
        estimate: 5,
        description: "New images and a new layout before the autumn campaign.",
        area: "Front page",
      },
      {
        title: "The menu could not be opened on mobile",
        column: "done",
        estimate: 2,
        area: "Front page",
        bug: true,
      },
    ],
    comment: "I can reproduce this on my own phone. Looking at it today.",
  },
  scrum: {
    name: "Member app",
    key: "APP",
    description:
      "The association's app for its members. Two-week sprints, demo every other Friday.",
    structure: {
      areas: ["Account", "Events", "Payment", "Messages"],
      themes: [
        { name: "Self-service", color: "moss" },
        { name: "Retention", color: "clay" },
        { name: "Regulatory", color: "rust" },
      ],
      epics: [
        {
          title: "Members can log in and see their membership",
          doneWhen: "90 % of members have logged in and seen their fee",
          area: "Account",
          themes: ["Self-service"],
          closed: true,
          features: [
            {
              title: "Members can log in with MitID",
              doneWhen: "Login works on iOS and Android and the fee is shown",
              closed: true,
            },
          ],
        },
        {
          title: "Members can sign up for events in the app",
          doneWhen: "Half of all sign-ups come from the app",
          area: "Events",
          themes: ["Retention"],
          quarterOffset: 0,
          features: [
            {
              title: "Members can sign up and cancel",
              doneWhen: "Sign-up, cancellation, reminder and waiting list all work",
            },
            {
              title: "Members can see an event's programme",
              doneWhen: "Time, place, programme and practical information are on the event's page",
              closed: true,
            },
          ],
        },
        {
          title: "Members can pay their fee in the app",
          doneWhen: "80 % of fee payments happen in the app",
          area: "Payment",
          themes: ["Self-service", "Regulatory"],
          quarterOffset: 1,
          features: [
            {
              title: "Members can pay by card",
              doneWhen: "A card payment completes and is receipted within a minute",
            },
            {
              title: "Members can see their payments",
              doneWhen: "Every payment from the last three years can be seen in the app",
            },
          ],
        },
        {
          title: "Members keep up to date through the app",
          doneWhen: "Push notifications are opened by at least a third of recipients",
          area: "Messages",
          themes: ["Retention"],
          quarterOffset: 2,
          features: [
            {
              title: "Members get push notifications",
              doneWhen: "Messages can be sent to everyone or to an event's participants",
            },
          ],
        },
        {
          title: "Members can look after their own membership",
          doneWhen:
            "Details are updated by the member, and the membership card is shown in the app",
          area: "Account",
          themes: ["Self-service", "Retention"],
          quarterOffset: 0,
          closed: true,
          features: [
            {
              title: "Members can edit their contact details",
              doneWhen:
                "Address, mail and phone can be edited in the app and reach the member register",
              closed: true,
            },
            {
              title: "Members can show their membership card",
              doneWhen:
                "The membership card can be shown without a connection and scanned at the door",
              closed: true,
            },
          ],
        },
      ],
    },
    pastSprints: [
      {
        name: "Sprint 1",
        goal: "Members can log in and see their membership fee",
        cards: [
          {
            title: "Login with MitID",
            estimate: 8,
            done: true,
            feature: "Members can log in with MitID",
          },
          {
            title: "Fee overview",
            estimate: 5,
            done: true,
            feature: "Members can log in with MitID",
          },
          {
            title: "Change password",
            estimate: 2,
            done: true,
            feature: "Members can log in with MitID",
          },
          { title: "Profile picture", estimate: 3, done: false, area: "Account" },
        ],
      },
      {
        name: "Sprint 2",
        goal: "Signing up for events",
        cards: [
          {
            title: "List of upcoming events",
            estimate: 5,
            done: true,
            feature: "Members can sign up and cancel",
          },
          {
            title: "Sign up and cancel",
            estimate: 8,
            done: true,
            feature: "Members can sign up and cancel",
          },
          {
            title: "Reminder the day before",
            estimate: 3,
            done: true,
            feature: "Members can sign up and cancel",
          },
          {
            title: "Waiting list",
            estimate: 5,
            done: false,
            feature: "Members can sign up and cancel",
          },
          { title: "Profile picture", estimate: 3, done: true, area: "Account" },
        ],
      },
      {
        name: "Sprint 3",
        goal: "Members update their own details",
        cards: [
          {
            title: "Edit address and phone number",
            estimate: 5,
            done: true,
            feature: "Members can edit their contact details",
          },
          {
            title: "Confirm a new mail address",
            estimate: 3,
            done: true,
            feature: "Members can edit their contact details",
          },
          {
            title: "Changes are sent to the member register",
            estimate: 5,
            done: true,
            feature: "Members can edit their contact details",
          },
          {
            title: "The address is not saved on Android",
            estimate: 2,
            done: true,
            feature: "Members can edit their contact details",
            bug: true,
          },
          { title: "Delete my account", estimate: 5, done: false, area: "Account" },
        ],
      },
      {
        name: "Sprint 4",
        goal: "The membership card is in the phone",
        cards: [
          {
            title: "Membership card with a barcode",
            estimate: 8,
            done: true,
            feature: "Members can show their membership card",
          },
          {
            title: "The membership card works offline",
            estimate: 5,
            done: true,
            feature: "Members can show their membership card",
          },
          {
            title: "Scanning at the door",
            estimate: 3,
            done: true,
            feature: "Members can show their membership card",
          },
          {
            title: "Membership card in Apple Wallet",
            estimate: 5,
            done: true,
            feature: "Members can show their membership card",
          },
          {
            title: "Automated tests of the membership card",
            estimate: 3,
            done: false,
            area: "Account",
            enabler: "architecture",
          },
        ],
      },
      {
        name: "Sprint 5",
        goal: "An event's programme in the app",
        cards: [
          {
            title: "A page for an event",
            estimate: 5,
            done: true,
            feature: "Members can see an event's programme",
          },
          {
            title: "Programme with times and speakers",
            estimate: 8,
            done: true,
            feature: "Members can see an event's programme",
          },
          {
            title: "Practical information on the event page",
            estimate: 3,
            done: true,
            feature: "Members can see an event's programme",
          },
          {
            title: "Automated tests of the membership card",
            estimate: 3,
            done: true,
            area: "Account",
            enabler: "architecture",
          },
          { title: "Map and directions to the venue", estimate: 5, done: false, area: "Events" },
        ],
      },
      {
        name: "Sprint 6",
        goal: "Events are easy to find and plan",
        cards: [
          { title: "Map and directions to the venue", estimate: 5, done: true, area: "Events" },
          { title: "Search and filter the events", estimate: 8, done: true, area: "Events" },
          { title: "Add an event to the calendar", estimate: 5, done: true, area: "Events" },
          {
            title: "Images in the programme are turned the wrong way",
            estimate: 2,
            done: true,
            feature: "Members can see an event's programme",
            bug: true,
          },
          {
            title: "Test environment at the payment provider",
            estimate: 3,
            done: true,
            feature: "Members can pay by card",
            enabler: "infrastructure",
          },
          { title: "Participant list for the organiser", estimate: 3, done: false, area: "Events" },
        ],
      },
    ],
    activeSprint: {
      name: "Sprint 7",
      goal: "Paying the membership fee in the app",
      cards: [
        {
          title: "Choose a payment method",
          estimate: 3,
          state: "done",
          mine: true,
          feature: "Members can pay by card",
        },
        {
          title: "Pay by card",
          estimate: 8,
          state: "doing",
          priority: "high",
          mine: true,
          feature: "Members can pay by card",
        },
        {
          title: "Receipt by mail",
          estimate: 2,
          state: "done",
          feature: "Members can pay by card",
        },
        {
          title: "Payment history",
          estimate: 5,
          state: "doing",
          feature: "Members can see their payments",
        },
        {
          title: "Waiting list",
          estimate: 5,
          state: "todo",
          feature: "Members can sign up and cancel",
        },
        {
          title: "Error messages when a payment is declined",
          estimate: 3,
          state: "todo",
          feature: "Members can pay by card",
          bug: true,
        },
      ],
    },
    backlog: [
      { title: "Push notifications", estimate: 8, feature: "Members get push notifications" },
      { title: "Share an event", estimate: 2, area: "Events" },
      { title: "Dark theme", estimate: 3, area: "Account" },
      { title: "Family membership", estimate: 13, area: "Account" },
      {
        title: "Automated tests of the login flow",
        estimate: 5,
        area: "Account",
        enabler: "architecture",
      },
      { title: "English language version", estimate: null, area: "Account" },
    ],
    plannedSprint: { name: "Sprint 8", goal: "Messages to members" },
  },
};
